Repository apmath-web/expenses, pull requests merged in 2019-05, with the labels that each got.

#31 Создать calculationService
  Domain/domainModelInterfaces.go
  Domain/models/ExpensesModel.go
  Domain/models/PersonDomainModel.go
  Domain/repositoriesInterface.go
  Domain/services/calulationService.go
  Infrastructure/ClientFetchService.go
Labels: ready

#34 Создать action и route
  .gitignore
  Application/actions/actionGetExpenses.go
  Application/actions/actions.go
  Application/routing/router.go
  Application/viewModels/ExpensesViewModel.go
  Application/viewModels/IdListViewModel.go
  Domain/services/calulationService.go
  Infrastructure/ClientFetchService.go
Labels: question, ready

#48 Change IdListViewModel and all dependeces
  Application/actions/actionGetExpenses.go
  Application/mapper/IdsMapper.go
  Application/mapper/TestIdsMapper_test.go
  Application/viewModels/IdListViewModel.go
Labels: approved

#50 Upadate validation
  Application/Validation/Validation.go
  Application/actions/actionGetExpenses.go
  Application/viewModels/IdListViewModel.go
Labels: approved
